### PR TITLE
NAs in ydt throw an error

### LINKED ISSUE #57: Terminator stagnation and an occasionally failing learner return an error during tuning
Hi,

I stumbled on this by chance, not sure if it can be classified as bug but I thought you should know about it.

When combined  with a learner that fails occasionally stagnation terminator returns the error:

```
Error in if (self$terminator$is_terminated(self)) { : 
  missing value where TRUE/FALSE needed
```

Example:

```
lrn_rpart <- lrn("classif.rpart")
ig <- po("filter", flt("information_gain"))

ps <- ParamSet$new(list(
  ParamDbl$new("classif.rpart.cp", lower = 0, upper = 0.05),
  ParamInt$new("information_gain.filter.nfeat", lower = 20L, upper = 60L),
  ParamFct$new("information_gain.type", levels = c("infogain",
                                                   "gainratio")) # I know gainratio does not work well with Sonar
))

glrn <- ig %>>%
  lrn_rpart

glrn <- GraphLearner$new(glrn) 

glrn$encapsulate <-  c(train = "evaluate", predict = "evaluate")

cv5 <- rsmp("cv", folds = 5)

tsk <- mlr_tasks$get("sonar")

instance <- TuningInstance$new(
  task = tsk,
  learner = glrn,
  resampling = cv5,
  measures = msr("classif.ce"),
  param_set = ps,
  terminator =  term("stagnation", iters = 5, threshold = 0)
)

tuner <- TunerRandomSearch$new()
set.seed(123)
tuner$tune(instance)
```

After 6 configurations evaluated the error occurs - I trust it is due to the `NaN` in the performance measure

```
instance$archive()
   nr batch_nr  resample_result task_id                     learner_id resampling_id iters params tune_x warnings errors classif.ce
1:  1        1 <ResampleResult>   sonar information_gain.classif.rpart            cv     5 <list> <list>        0      0  0.2648084
2:  2        2 <ResampleResult>   sonar information_gain.classif.rpart            cv     5 <list> <list>        0      0  0.2596980
3:  3        3 <ResampleResult>   sonar information_gain.classif.rpart            cv     5 <list> <list>        0      5        NaN
4:  4        4 <ResampleResult>   sonar information_gain.classif.rpart            cv     5 <list> <list>        0      0  0.2454123
5:  5        5 <ResampleResult>   sonar information_gain.classif.rpart            cv     5 <list> <list>        0      0  0.2501742
6:  6        6 <ResampleResult>   sonar information_gain.classif.rpart            cv     5 <list> <list>        0      0  0.2737515
```

All the best,

Milan

### PR DESCRIPTION
**Pull request by be-marc**
Closes #57

```
Assertion on 'y' failed: Contains missing values (element 1). 
```

Is this enough or do we need a more informative message for the user?

### CODE REVIEW

File: R/Archive.R [hunk 1]
```diff
@@ -43,17 +43,16 @@ Archive = R6Class("Archive",
     #'
     #' @param xss_trafoed (`list()`).
     add_evals = function(xdt, xss_trafoed, ydt) {
-
-      # FIXME: add checks here for the dts and their domains
-      # FIXME: make asserts better!
       assert_data_table(xdt)
       assert_data_table(ydt)
       assert_list(xss_trafoed)
+      map(ydt[, self$cols_y, with = FALSE], function(y) {
```
Comment (jakob-r) [inline R/Archive.R:49]: Can you please use `check_data_table(..., any.missing = FALSE)` instead?

Comment (be-marc) [reply R/Archive.R]: Thanks.I did not know about this. But we want to use `assert_data_table`, right?
